import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException; 
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class BottomReportView extends javax.swing.JFrame {
    public static Connection con = null; 
    public static Statement st = null; 
    public static ResultSet rs;

    /**
     * Creates new form BottomReportView
     */
    public BottomReportView() {
        initComponents();
        setLocationRelativeTo(null);
        koneksimysql();
        tampiltabel();
    }

     public void koneksimysql(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/db_tubespbo", "root", "");
            st = con.createStatement();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Connection Failed!");
        }
    }
     
    DefaultTableModel tb;
    public void tampiltabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("OrderId");
        tb.addColumn("Username");
        tb.addColumn("TotalPayment");
        tb.addColumn("OrderStatus");
        tb.addColumn("PaymentStatus");
        tb.addColumn("Date");
        tb.addColumn("PhoneNumber");
        tableOrder.setModel(tb); 
        
        try{
            String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username`;");
            rs = st.executeQuery(sql);
            while (rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("OrderId"),
                    rs.getString("Username"),
                    rs.getString("TotalPayment"),
                    rs.getString("OrderStatus"),
                    rs.getString("PaymentStatus"),
                    rs.getString("OrderDate"), 
                    rs.getString("PhoneNumber")
                });   
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Failed to show data! " +e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAccount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        buttonOS = new javax.swing.JButton();
        buttonPS = new javax.swing.JButton();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        labelBack = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        OrderView = new javax.swing.JButton();
        cbShowOrders = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(730, 430));
        jPanel1.setLayout(null);

        labelAccount.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        labelAccount.setText("Account");
        labelAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAccountMouseClicked(evt);
            }
        });
        jPanel1.add(labelAccount);
        labelAccount.setBounds(1338, 30, 65, 19);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel17.setText("X");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(896, 0, 24, 20);

        labelExit.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });
        jPanel1.add(labelExit);
        labelExit.setBounds(708, 0, 21, 20);

        tableOrder.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableOrder);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 61, 591, 200);

        buttonOS.setBackground(new java.awt.Color(255, 255, 255));
        buttonOS.setFont(new java.awt.Font("Mermaid", 0, 14)); // NOI18N
        buttonOS.setText("<html>order by <br>order status");
        buttonOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOSActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOS);
        buttonOS.setBounds(120, 370, 150, 39);

        buttonPS.setBackground(new java.awt.Color(255, 255, 255));
        buttonPS.setFont(new java.awt.Font("Mermaid", 0, 14)); // NOI18N
        buttonPS.setLabel("<html>order by <br>payment status ");
        buttonPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPSActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPS);
        buttonPS.setBounds(120, 320, 150, 39);

        kGradientPanel7.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 36, 16));
        kGradientPanel7.setPreferredSize(new java.awt.Dimension(110, 85));

        jLabel13.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("<html>Top <br>Order");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        labelBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setText("<<<");
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("<html>Bottom<br>Order");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("<html>Top <br>Order<br>Report");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("<html>Bottom <br>Order<br>Report");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelBack))
                    .addGroup(kGradientPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addComponent(labelBack)
                .addGap(41, 41, 41)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(kGradientPanel7);
        kGradientPanel7.setBounds(0, 0, 110, 430);

        OrderView.setBackground(new java.awt.Color(255, 255, 255));
        OrderView.setFont(new java.awt.Font("Mermaid", 0, 18)); // NOI18N
        OrderView.setLabel("<html>order<br>view >>>");
        OrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderViewActionPerformed(evt);
            }
        });
        jPanel1.add(OrderView);
        OrderView.setBounds(602, 336, 109, 57);

        cbShowOrders.setFont(new java.awt.Font("Mermaid", 0, 14)); // NOI18N
        cbShowOrders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show Orders", "Unpaid Orders", "Paid Orders", "Completed Orders", "On Proceed Orders", "Cancelled Orders" }));
        cbShowOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowOrdersActionPerformed(evt);
            }
        });
        jPanel1.add(cbShowOrders);
        cbShowOrders.setBounds(120, 280, 147, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseClicked
        // TODO add your handling code here:
        Account acc= new Account();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelAccountMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableOrderMouseClicked

    private void buttonOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOSActionPerformed
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("OrderId");
        tb.addColumn("Username");
        tb.addColumn("TotalPayment");
        tb.addColumn("OrderStatus");
        tb.addColumn("PaymentStatus");
        tb.addColumn("Date");
        tb.addColumn("PhoneNumber");
        tableOrder.setModel(tb);

        try{
            String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` order by OrderStatus;");
            rs = st.executeQuery(sql);
            while (rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("OrderId"),
                    rs.getString("Username"),
                    rs.getString("TotalPayment"),
                    rs.getString("OrderStatus"),
                    rs.getString("PaymentStatus"),
                    rs.getString("OrderDate"), 
                    rs.getString("PhoneNumber")
                });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Failed to show data! " +e.getMessage());
        }
    }//GEN-LAST:event_buttonOSActionPerformed

    private void buttonPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPSActionPerformed
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("OrderId");
        tb.addColumn("Username");
        tb.addColumn("TotalPayment");
        tb.addColumn("OrderStatus");
        tb.addColumn("PaymentStatus");
        tb.addColumn("Date");
        tb.addColumn("PhoneNumber");
        tableOrder.setModel(tb);

        try{
            String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` order by PaymentStatus;");
            rs = st.executeQuery(sql);
            while (rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("OrderId"),
                    rs.getString("Username"),
                    rs.getString("TotalPayment"),
                    rs.getString("OrderStatus"),
                    rs.getString("PaymentStatus"),
                    rs.getString("OrderDate"),
                    rs.getString("PhoneNumber")
                });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Failed to show data! " +e.getMessage());
        }   
    }//GEN-LAST:event_buttonPSActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new TopReportView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        DashboardAdmin da= new DashboardAdmin();
        da.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelBackMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new BottomReportView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        TopOrder a= new TopOrder();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        BottomOrder a= new BottomOrder();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void OrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderViewActionPerformed
        // TODO add your handling code here:
        BottomOrderView a= new BottomOrderView();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_OrderViewActionPerformed

    private void cbShowOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowOrdersActionPerformed
        // TODO add your handling code here:
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("OrderId");
            tb.addColumn("Username");
            tb.addColumn("TotalPayment");
            tb.addColumn("OrderStatus");
            tb.addColumn("PaymentStatus");
            tb.addColumn("Date");
            tb.addColumn("PhoneNumber");
            tableOrder.setModel(tb);

            try{
                if(cbShowOrders.getSelectedItem()=="Unpaid Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` where PaymentStatus='Unpaid';");
                    rs = st.executeQuery(sql);
                }
                else if (cbShowOrders.getSelectedItem()=="Paid Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` where PaymentStatus='Paid';");
                    rs = st.executeQuery(sql);
                }
                else if (cbShowOrders.getSelectedItem()=="On Proceed Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` where OrderStatus='To be proceed';");
                    rs = st.executeQuery(sql);
                }
                else if (cbShowOrders.getSelectedItem()=="Completed Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` where OrderStatus='Completed';");
                    rs = st.executeQuery(sql);
                }
                else if (cbShowOrders.getSelectedItem()=="Cancelled Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username` where OrderStatus='Cancelled';");
                    rs = st.executeQuery(sql);
                }
                else if (cbShowOrders.getSelectedItem()=="Show Orders"){
                    String sql = ("SELECT orderid, tb_OrderBottom.username, TotalPayment, orderstatus, PaymentStatus, orderdate, tb_register.`PhoneNumber` FROM tb_orderBottom JOIN tb_register ON tb_register.username=tb_orderBottom.`Username`;");
                    rs = st.executeQuery(sql);
                }
                while (rs.next()){
                    tb.addRow(new Object[]{
                        rs.getString("OrderId"),
                        rs.getString("Username"),
                        rs.getString("TotalPayment"),
                        rs.getString("OrderStatus"),
                        rs.getString("PaymentStatus"),
                        rs.getString("OrderDate"),
                        rs.getString("PhoneNumber")
                    });
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Failed to show data! " +e.getMessage());
            }
        
    }//GEN-LAST:event_cbShowOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BottomReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BottomReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BottomReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BottomReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BottomReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OrderView;
    private javax.swing.JButton buttonOS;
    private javax.swing.JButton buttonPS;
    private javax.swing.JComboBox<String> cbShowOrders;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelExit;
    private javax.swing.JTable tableOrder;
    // End of variables declaration//GEN-END:variables
}
